language: python
python:
  - "3.8"
install:
  - pip install coverage
  - pip install -r requirements.txt
  - python setup.py install
script:
  - pytest drop
  - pytest integration_tests
  - cd docs; make html

after_success:
  - pip install coveralls
  - coveralls
